name: Nix

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    # the only supported system by coursier and sbt on nixpkgs
    strategy:
      matrix:
        system: ['x86_64-linux']

    steps:
      - uses: actions/checkout@v4

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v31.2.0

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v16
        with:
          name: profunktor
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Nix flake check ❄️"
        run: |
          nix flake check --all-systems -L
          nix build .#sbt -L

      - name: "Nix devshell build for ${{ matrix.system }} ❄️"
        run: nix build .#devShells.${{ matrix.system }}.default.inputDerivation
