name: Nix

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v31.2.0

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v16
        with:
          name: profunktor
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Nix flake check ❄️"
        run: |
          nix flake check --all-systems -L
          nix buil .#sbt -L
